### ISSUE TITLE
Cannot set property 'defaultVersionStrategy' on null object

### ISSUE THREAD

**Issue by polarcoral** [nebula-plugins/gradle-netflixoss-project-plugin#35]
when I use nebula.netflixoss plugin  as below:
plugins {
    id 'nebula.netflixoss' version '3.5.2'
}

error occurs:
* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '3.5.2']
> Failed to apply plugin [id 'nebula.netflixoss']
   > Cannot set property 'defaultVersionStrategy' on null object

Anyone can tell me why?

**Comment by DanielThomas** [comment]
Which project @polarcoral?

**Comment by polarcoral** [comment]
https://github.com/Netflix/zuul

**Comment by DanielThomas** [comment]
That's a pretty old plugin and Gradle version. Upgrade both the Gradle wrapper and plugin to the latest version. Contact us on Slack if you need anything else.
